trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: GCPJob
  displayName: 'Authenticate to GCP using raw JSON'
  steps:
  - checkout: self

  - task: Bash@3
    displayName: "Write JSON key to file"
    inputs:
      targetType: 'inline'
      script: |
        echo "$GCLOUD_KEY_JSON" > key.json

        if [ ! -s key.json ]; then
          echo "❌ key.json is empty — your secret did not pass correctly."
          exit 1
        fi

        echo "✅ JSON key written"
        cat key.json

        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project extreme-minutia-492415-v6

  - task: Bash@3
    displayName: "GCP Test Command"
    inputs:
      targetType: 'inline'
      script: |
        gcloud iam service-accounts list --project=extreme-minutia-492415-v6