trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: GCP_job
  displayName: 'GCP_job'
  steps:
  - checkout: self
  
  - task: Bash@3
    displayName: "Authenticate to GCP"
    inputs:
      targetType: 'inline'
      script: |
        printf "%s" "$(GCLOUD_KEY_JSON)" > key.json
        cat key.json        # Optional: debugging if allowed
        gcloud auth activate-service-account --key