---
- name: Configure User using gcloud CLI (No Collection)
  hosts: localhost  # If running ON the VM itself
  become: true
  
  tasks:
    - name: Fetch password from Secret Manager
      # 'gcloud' uses the VM's attached identity automatically
      ansible.builtin.shell: >
        gcloud secrets versions access latest --secret="my-pass"
      register: secret_output
      no_log: true # Prevents the password from appearing in Ansible logs
      become: false

    - name: Ensure the current user is in the wheel group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: wheel
        append: yes
        # Use the captured output from the gcloud command
        password: "{{ secret_output.stdout | password_hash('sha512') }}"
      no_log: true
      

    - name: Enable Password Authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
